application:
  name: auto-market

spring:
  flyway:
    schemas: public
    validate-on-migrate: false
    baseline-on-migrate: true
    validate-migration-naming: true
  mvc:
    throw-exception-if-no-handler-found: true
  output.ansi.enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    maximumPoolSize: 10
    minimumIdle: 5
    idleTimeout: 10000


springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /private/swagger-ui
    config-url: /api-docs/swagger-config
    disable-swagger-default-url: true
    urls[0]:
      url: /api-docs

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
